### PR TITLE
Pass arguments on without splicing into an array

### PR DESCRIPTION
**Pull request by ForbesLindesay**
I'm not aware of any browser compatibility issues with calling `fn.apply(null, arguments)` where arguments is "array like" rather than a true array.

### CODE REVIEW

**Comment by dominictarr** [comment]
you don't mention the reason for this change - is this a compatibility issue?

**Comment by ForbesLindesay** [comment]
No, it just seemed cleaner.  I don't mind especially and it's non-urgent, I was just reading through the code and this seems to me to be a lot simpler and cleaner.

**Comment by ForbesLindesay** [comment]
Probably performs better too, not that this function is likely to be a bottle neck.

**Comment by dominictarr** [comment]
ah, okay. this module is stable, so I am not gonna merge any changes that are not fixes (excepting to documentation)

**Comment by ForbesLindesay** [comment]
Fair enough

**Pull request closed without merging**
